#!/usr/bin/env php
<?php

require ($GLOBALS['_composer_autoload_path'] ?? __DIR__ . '/../../autoload.php');

use jahndigital\Typo3Automation\Commands\ControllerCommand;
use jahndigital\Typo3Automation\Commands\ModelCommand;
use jahndigital\Typo3Automation\Commands\RepositoryCommand;

$command = $argv[1] ?? null;
$mainDirectory = $argv[2] ?? null;

if (!$mainDirectory) {
    echo "Main directory is required.\n";
    exit(1);
}
switch ($command) {
    case 'make:model':
        ModelCommand::handle($argv, $mainDirectory);
        break;
    case 'make:controller':
        ControllerCommand::handle($argv, $mainDirectory);
        break;
    case 'make:repository':
        RepositoryCommand::handle($argv, $mainDirectory);
        break;
    default:
        echo "Invalid command\n";
        break;
}
