#!/usr/bin/env php
<?php

require ($GLOBALS['_composer_autoload_path'] ?? __DIR__ . '/../../autoload.php');

use jahndigital\Typo3Automation\Commands\ControllerCommand;
use jahndigital\Typo3Automation\Commands\ModelCommand;
use jahndigital\Typo3Automation\Commands\RepositoryCommand;

$command = $argv[1] ?? null;

switch ($command) {
    case 'make:model':
        ModelCommand::handle($argv);
        break;
    case 'make:controller':
        ControllerCommand::handle($argv);
        break;
    case 'make:repository':
        RepositoryCommand::handle($argv);
        break;
    default:
        echo "Invalid command\n";
        break;
}
