#!/usr/bin/env php
<?php

if (file_exists($a = __DIR__ . '/vendor/autoload.php')) {
    require $a;
} elseif (file_exists($a = getenv('COMPOSER_HOME') . '/vendor/autoload.php')) {
    require $a;
} else {
    // Handle the error if autoload.php is not found
    echo "Autoload file not found";
    exit(1);
}

use jahndigital\Classes\Commands\ControllerCommand;
use jahndigital\Classes\Commands\ModelCommand;
use jahndigital\Classes\Commands\RepositoryCommand;

$command = $argv[1] ?? null;

switch ($command) {
    case 'make:model':
        ModelCommand::handle($argv);
        break;
    case 'make:controller':
        ControllerCommand::handle($argv);
        break;
    case 'make:repository':
        RepositoryCommand::handle($argv);
        break;
    default:
        echo "Invalid command\n";
        break;
}
